# Site settings
title: kimsoojin
email: rlatnwls0611@gmail.com
url: https://kimsoojin.github.io/portfolio
description: "GIS Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/kim.sujin.547
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
# - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/kimsoojin

# Build settings
markdown: kramdown
permalink: pretty
